package com.spanel.dao;

import java.sql.ResultSet;
import java.sql.SQLException;

import static com.spanel.dao.DAOUtilitary.initPreparedStatement;
import static com.spanel.dao.DAOUtilitary.silentClose;

/**
 * Created by koria on 06/01/2017.
 */
public class AffectationFileDAOImpl implements AffectationFileDAO {
    DAOFactory daoFactory;
    public static String SQL_INSERT ="INSERT INTO affectation_files(affectation_id,file_id,type) VALUES(?,?,?)";

    public AffectationFileDAOImpl(DAOFactory daoFactory) {this.daoFactory = daoFactory ;
    }

    @Override
    public void create(Long affectationId,Long fileId,String type) throws DAOException {
        java.sql.Connection connection = null;
        java.sql.PreparedStatement preparedStatement = null;
        ResultSet AutoGeneratedValue = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initPreparedStatement(connection, SQL_INSERT, true, affectationId, fileId,type);
            int status = preparedStatement.executeUpdate();
            if (status == 0) {
                throw new DAOException("Failed to create schedule in database,No id auto generated value  ");
            }
        } catch (SQLException e) {
            throw new DAOException(e);
        } finally {
            silentClose(preparedStatement);
            silentClose(AutoGeneratedValue);
            silentClose(connection);
        }
    }
}
