package com.spanel.dao;

import com.spanel.beans.Announce;
import com.spanel.beans.User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static com.spanel.dao.DAOUtilitary.initPreparedStatement;
import static com.spanel.dao.DAOUtilitary.silentClose;

/**
 * Created by koria on 21/12/2016.
 */
public class AnnounceDAOImpl implements AnnounceDAO {
    private static final String SQL_INSERT = "INSERT INTO announces(class_id, author_id,title,type,description,expiration_date,date) VALUES(?,?,?,?,?,?,NOW())";
    private static final String SQL_FIND_ALL = "SELECT * FROM announces";
    private static final String SQL_FIND_CLASSES_ANNOUNCES = "SELECT * FROM announces WHERE class_id = ? ORDER BY date DESC";
    private static final String SQL_FIND_BY_TITLE =" SELECT * FROM announces WHERE title = ?";
    private static final String SQL_UPDATE ="UPDATE announces SET class_id = ?,author_id = ?,title = ?,type = ?,description = ?,expiration_date = ?,date= NOW() WHERE id = ?";

    private DAOFactory daoFactory;

    public AnnounceDAOImpl(DAOFactory daoFactory) {
        this.daoFactory = daoFactory;
    }

    @Override
    public void create(Announce announce) throws DAOException {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet AutoGeneratedValue = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initPreparedStatement(connection, SQL_INSERT, true, announce.getClassId(), announce.getAuthorId(), announce.getTitle(), announce.getType(), announce.getDescription(), announce.getExpirationDate());
            int status = preparedStatement.executeUpdate();
            if (status == 0) {
                throw new DAOException("Erreur lors de la création de l'announce, aucune nouvelle ligne n'a été ajoutée !");
            }
            AutoGeneratedValue = preparedStatement.getGeneratedKeys();
            if (AutoGeneratedValue.next()) {
                announce.setId(AutoGeneratedValue.getLong(1));
            } else {
                throw new DAOException("Echec de la création du classroom");
            }
        } catch (SQLException e) {
            throw new DAOException(e);
        } finally {
            silentClose(preparedStatement);
            silentClose(AutoGeneratedValue);
            silentClose(connection);
        }
    }

    public List<Announce> findByClassId(Long classId){
        return findMany(SQL_FIND_CLASSES_ANNOUNCES,classId);
    }



    private List<Announce> findMany(String sql, Object... objects ) throws DAOException{
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Announce> announces = new ArrayList<>();

        try {
            connection = daoFactory.getConnection();
            preparedStatement = initPreparedStatement( connection, sql, false, objects );
            resultSet = preparedStatement.executeQuery();
            while ( resultSet.next() ) {
                announces.add(map( resultSet )) ;
            }
        } catch ( SQLException e ) {
            throw new DAOException( e );
        } finally {
            silentClose( resultSet, preparedStatement, connection );
        }

        return announces;
    }


    @Override
    public void update(Long id) throws DAOException {
    }

    @Override
    public Class find(Long id) throws DAOException {
        return null;
    }

    @Override
    public List<Announce> findAll() throws DAOException {
        return findMany(SQL_FIND_ALL);
    }

    @Override
    public List<Announce> findAll(User user) throws DAOException {
        return null;
    }


    @Override
    public Announce findByTitle(String title) {

        return find(SQL_FIND_BY_TITLE,title);
    }

    @Override
    public void update(Announce announce) throws DAOException {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet AutoGeneratedValue = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initPreparedStatement(connection, SQL_UPDATE,false, announce.getClassId(), announce.getAuthorId(), announce.getTitle(), announce.getType(), announce.getDescription(), announce.getExpirationDate(),announce.getId());
            int status = preparedStatement.executeUpdate();
            if (status == 0) {
                throw new DAOException("Erreur lors de la modification de l'announce, la ligne n'a pas été modifie !");
            }
        } catch (SQLException e) {
            throw new DAOException(e);
        } finally {
            silentClose(preparedStatement);
            silentClose(AutoGeneratedValue);
            silentClose(connection);
        }
    }

    private Announce find(String sql, Object... objects) throws DAOException{
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;
        Announce announce = null;
        try {
            connection = daoFactory.getConnection();
            statement = initPreparedStatement(connection,sql,false,objects);
            resultSet = statement.executeQuery();
            while (resultSet.next()){
                announce = map(resultSet);
            }
        } catch (SQLException e) {
            throw new DAOException(e);
        }
        finally {
            silentClose(resultSet,statement,connection);
        }
        return announce;
    }



    public static Announce map(ResultSet resultSet) throws SQLException {
        Announce announce = new Announce();
        announce.setId(resultSet.getLong("id"));
        announce.setClassId(resultSet.getLong("class_id"));
        announce.setAuthorId(resultSet.getLong("author_id"));
        announce.setTitle(resultSet.getString("title"));
        announce.setType(resultSet.getString("type"));
        announce.setDescription(resultSet.getString("description"));
        announce.setDate(resultSet.getDate("date"));
        announce.setExpirationDate(resultSet.getDate("expiration_date"));
        return announce;
    }
}
