package com.spanel.dao;

import com.spanel.beans.Schedule;
import com.spanel.beans.Schedule;


import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import static com.spanel.dao.DAOUtilitary.initPreparedStatement;
import static com.spanel.dao.DAOUtilitary.silentClose;

/**
 * Created by koria on 30/12/2016.
 */
public class ScheduleDAOImpl implements ScheduleDAO {
    private DAOFactory daoFactory;

    public ScheduleDAOImpl(DAOFactory daoFactory) {
        this.daoFactory = daoFactory;
    }

    private static String SQL_INSERT = "INSERT INTO schedules(class_id,file_id) VALUES(?,?)";
    private static String SQL_FIND_ALL_SCHEDULE = "SELECT files.id,files.author_id,files.name,files.path,files.date FROM files WHERE files.id IN(SELECT id FROM schedules) ORDER BY id DESC ";

    @Override
    public void create(Schedule schedule) throws DAOException {
        java.sql.Connection connection = null;
        java.sql.PreparedStatement preparedStatement = null;
        ResultSet AutoGeneratedValue = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initPreparedStatement(connection, SQL_INSERT, true, schedule.getClassId(), schedule.getFileId());
            int status = preparedStatement.executeUpdate();
            if (status == 0) {
                throw new DAOException("Failed to create schedule in database,No id auto generated value  ");
            }
            AutoGeneratedValue = preparedStatement.getGeneratedKeys();
            if (AutoGeneratedValue.next()) {
                schedule.setId(AutoGeneratedValue.getLong(1));
            } else {
                throw new DAOException("Failed to create schedule in database,No id auto generated value  ");

            }
        } catch (SQLException e) {
            throw new DAOException(e);
        } finally {
            silentClose(preparedStatement);
            silentClose(AutoGeneratedValue);
            silentClose(connection);
        }
    }


}
